url: "https://portfolio.sinoper.dev"
title: "Jess' Portfolio"
description: '[wip]'

collections:
  sinoper-v1:
    output: true
    sort_by: index
  sinoper-v2:
    output: true
    order:
      - index.md
      - command-core.md
      - Connections/index.md
      - Connections/tw-user.md
      - Connections/tw-api.md
      - Connections/discord-user.md
      - Connections/mongo.md
      - Connections/overlay-server.md
      - Connections/spotify.md
      - overlay-client.md
  library:
    output: true
    sort_by: index
  modding:
    output: true
    sort_by: index
  storyteller:
    output: true
    sort_by: index

collections_dir: projects

permalink: /:categories/:slug
