url: "https://portfolio.sinoper.dev"
title: "Jess' Portfolio"
description: '[wip]'

collections:
  sinoper-v1:
    output: true
    sort_by: index
  sinoper-v2:
    output: true
    sort_by: index
  library:
    output: true
    sort_by: index
  modding:
    output: true
    sort_by: index
  storyteller:
    output: true
    sort_by: index

collections_dir: projects

permalink: /:categories/:slug
